### ISSUE TITLE
Username option for scraping tweets

### ISSUE THREAD

**Issue by aditi1421** [Nirmal-Data-Scientist/Twitter_Scraping#1]
Hi!
I wanted to add another option for username as well, and I did end up adding it in the python file that I forked but whenever I host it, the changes are not updated.
What change do I need to make for the same to be reflected when I host it?

**Comment by nirmals-workspace** [comment]
Hai Aditi.... Glad you found some value in my project.... Now may I know where you are trying to host it? In the local server or the cloud one?

Also please let me know which library you are using, is it the same snscrape library that I used or some other scraping tool? If it is snscrape there's an ongoing issue which would raise Error:403.... This is because twitter has blocked snscrape from scraping their content and the issue started arising 1 month back and it is yet to be resolved as far as I know and I am planning to overcome this issue by moving on to some other library. But I am yet to find some time for it..... 

Also the username thing.... Is it not appearing in the streamlit app or throwing some error? If you are getting error if you can share with me a screenshot of the error and the code snippet where you inserted the username textbox, kindly share with me those two so that I could try and help you in some possible ways....


Thanks and Regards,
Nirmal

**Comment by aditi1421** [comment]
I tried to host it on streamlit, it's not working correctly but still somewhere, I will create pr so that you can see the change as well.
YEAH! It's a huge issue that snscrape is not working or limits user to the number of tweets it can scrape. Somehow, the site is working for me but the results are inaccurate/requires a lot of data cleaning.  Twitter has recently blocked all third party applications and requires people to buy twitter api in order to access data. None of the python libraries work as well.

**Comment by nirmals-workspace** [comment]
Hey Aditi! Thanks for raising an issue.... Otherwise I wouldn't have touched it any sooner.... Now I have made a complete overhaul... Have a look at my app now and do ping me if you encounter any other issues... I have added username feature as well to the app... I am leaving the app badge below...

[![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://nirmal-data-scientist-twitter-data-fetching.streamlit.app/)

Thanks and regard,
Nirmal
